### ISSUE TITLE
Developing Algorithmic ideas

### ISSUE THREAD

**Issue by bfmags** [Greennav/range-anxiety#1]
Develop algorithmic ideas, based on very simple algorithms, namely Dijkstra and A*, taking the data from the database. These will be specialised to consider energy consumption.

**Comment by LeahAC** [comment]
A simplified demonstration highlighting Dijkstra's algorithm to determine the shortest distance between 2 cities in England is attempted. Some major cities in the U.K are selected and the algorithm runs on this data. 

Please note: The graph is no way determines the real transport communication system between the cities of England.  In many cases, there are direct links between any 2 cities in the real transport system of London. This graph has been simplified to suit our requirements and its sole purpose is to demonstrate the shortest path algorithm. The data can always be updated while the algorithm remains the same.
![nodes](https://user-images.githubusercontent.com/25109993/27394198-3bd6ac0e-56a3-11e7-802d-b408b1d27c9d.png)
.

**Comment by LeahAC** [comment]
The shortest path between Southampton and Birmingham is shown in yellow. The weights (a requirement of Dijkstra's algorithm) are the distances (in miles) between any two cities.

<img width="1004" alt="screen shot 2017-06-21 at 16 45 43" src="https://user-images.githubusercontent.com/25109993/27394388-dd12f32a-56a3-11e7-8f9a-4f794e88e280.png">
<img width="907" alt="screen shot 2017-06-21 at 16 46 25" src="https://user-images.githubusercontent.com/25109993/27394389-dd2ab5be-56a3-11e7-862b-f690d1286ebb.png">

**Comment by bfmags** [comment]
@LeahAC I think we can close this one, as this discussion is included in your first report 👍
