### ISSUE TITLE
fixed set of server exceptions

### ISSUE THREAD

**Issue by bfmags** [Greennav/range-anxiety#11]
Create fixed set of server exception covering all kinds of errors on the server-side -- missing parameters, exceptions like invalid coordinates(eg. not a road)

**Comment by bfmags** [comment]
Implemented and merged -> cabdaa0dd71cc58edbb2f72d35f8f541af264cbe

**Comment by LeahAC** [comment]
<img width="592" alt="screen shot 2017-08-10 at 22 06 59" src="https://user-images.githubusercontent.com/25109993/29192203-775cbcae-7e18-11e7-898e-7b58fe035e3d.png">
<img width="598" alt="screen shot 2017-08-10 at 22 07 19" src="https://user-images.githubusercontent.com/25109993/29192207-7cc7ca08-7e18-11e7-99cc-7ea936d6e6e9.png">

Error with messages.

**Comment by bfmags** [comment]
Looks good! :) 
@schoenfr any other exceptions you can think of that would be useful to have?
Thanks!

**Comment by bfmags** [comment]
Wrapping up. This looks good and be extended later 👍  Thanks @LeahAC
