### ISSUE TITLE
Polygon sketch

### ISSUE THREAD

**Issue by LeahAC** [Greennav/range-anxiety#2]
The polygon shown alongside uses SQL query to determine the coordinates of all U.K cities starting with 'A' within a distance of 30-50 miles from a chosen coordinate (which is 51.83440,0.91066, shown as a pink point in the map). 

```
 SELECT
name, latitude, longitude,(
3959 * acos (
cos ( radians(51.83440) )
* cos( radians( latitude ) )
* cos( radians( longitude ) - radians(0.91066) ) + sin ( radians(51.83440) )
* sin( radians( latitude ) )
)
) AS distance
FROM uk_towns
HAVING distance >30 && distance < 50
ORDER BY distance LIMIT 0 , 50;
```
> ![image](https://user-images.githubusercontent.com/3740101/27387308-49320b18-5690-11e7-951d-2cb57c64607c.png)
> _image shows only top 5 results_

The map contains contains only 50 small blue circles. These are the 50 U.K cities starting with 'A' which are nearest to the chosen coordinate within the range of 30-50 miles. 

**An important assumption is that the driver always intends to reach a city. Because it is range anxiety, the polygon boundary will necessarily end in a city and not in an arbitrary location.** 

![image](https://user-images.githubusercontent.com/3740101/27387199-f01af31e-568f-11e7-8346-843ba5392443.png)

**Comment by LeahAC** [comment]
This map along with the 2 polygons (orange and green) captures the uncertainty in the range. It is a little more detailed and includes the names of major cities along with some physical features of the U.K. 

The centre (having coordinates 51.61351 ,-2.45223, shown in blue) is a place called Abbotshire in Gloucestershire.

<img width="1023" alt="closeup" src="https://user-images.githubusercontent.com/25109993/27383861-b594647e-5684-11e7-872c-e8b518807e7d.png">
<img width="781" alt="distant" src="https://user-images.githubusercontent.com/25109993/27383862-b5ab0454-5684-11e7-8487-df8039f5f3a0.png">

**Comment by bfmags** [comment]
Closing this one -> reviewed on the first gsoc report 👍
