### ISSUE TITLE
Meaningful Readme

### ISSUE THREAD

**Issue by fabianbormann** [Greennav/range-anxiety#3]

**Comment by bfmags** [comment]
Hi @fabianbormann 
A small descriptive text was added to the readme (to be extended as the project evolves). 
Is it OK to close this one?

**Comment by bfmags** [comment]
@LeahAC 
The current small descriptive text in the Readme works Ok, but we can add the API reference (route, request parameters, response), example and setup instructions.

**Comment by bfmags** [comment]
ca65b88588c18c516a10ed287ef786be53a84123 works great.
Thanks @LeahAC -> Closing this now 👍

**Comment by fabianbormann** [comment]
👍
